# Generated by Django 2.0.2 on 2018-03-05 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='starter',
            field=models.ForeignKey(null=True, on_delete='', related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
