# Generated by Django 2.0.2 on 2018-03-05 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180305_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete='', related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
